
title: Pygmeeweb
description:

url: https://pygmeeweb.com
language: en

name: Pygmeeweb
markdown: kramdown

kramdown:
  input: GFM

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/news/:title/"
      layout: "post"

disqus_shortname: pygmeeweb

recent_posts: 50  # Posts on home page

